# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

pool:
 vmImage: 'ubuntu-20.04'
steps:
- task: JFrogNpm@1
 inputs:
   command: 'pack and publish'
   artifactoryConnection: 'jordanta-rt'
   targetRepo: 'shivani-npm-local'
   workingFolder: 'npm3/'
   collectBuildInfo: true
   buildName: '$(Build.DefinitionName)'
   buildNumber: '$(Build.BuildNumber)'
- task: JFrogPublishBuildInfo@1
 inputs:
   artifactoryConnection: 'jordanta-rt'
   buildName: '$(Build.DefinitionName)'
   buildNumber: '$(Build.BuildNumber)'
- task: JFrogBuildPromotion@1
 inputs:
   artifactoryConnection: 'jordanta-rt'
   buildName: '$(Build.DefinitionName)'
   buildNumber: '$(Build.BuildNumber)'
   targetRepo: 'jordanta-npm-local'
   status: 'Released'
   comment: 'Released'
   sourceRepo: 'shivani-npm-local'
   includeDependencies: false
   copy: true
   dryRun: false
