# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: JFrogNpm@1
  inputs:
    command: 'pack and publish'
    artifactoryConnection: 'jordanta-rt'
    targetRepo: 'jordanta-npm-local'
    workingFolder: '/Users/jordanta/Desktop/Tests/azure-npm'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'jordanta-rt'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogBuildPromotion@1
  inputs:
    artifactoryConnection: 'jordanta-rt'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'jordanta-npm-local'
    status: 'Released'
    includeDependencies: false
    copy: false
    dryRun: false
